// app/collection/[id]/CollectionInventoryPartCard.tsx
'use client';

import { FormEvent } from 'react';
import Image from 'next/image';
import { ToyBrick } from 'lucide-react';

import {
  Card,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { CollectionInventoryPart } from '@/models/CollectionInventoryPart';
import useAddCollectionInventoryPart from '@/mutations/useAddCollectionInventoryPart';

interface CollectionInventoryPartCardProps {
  collectionInventoryPart: CollectionInventoryPart;
}

function CollectionInventoryPartCard({
  collectionInventoryPart,
}: CollectionInventoryPartCardProps) {
  const { mutate: addCollectionInventoryPart, isLoading } =
    useAddCollectionInventoryPart(collectionInventoryPart);
  const { inventoryPart } = collectionInventoryPart;
  const { part } = inventoryPart;

  function onSubmit(event: FormEvent<HTMLFormElement>) {
    console.log('onSubmit');
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const count = parseInt(formData.get('quantity') as string, 10);
    addCollectionInventoryPart(count);
  }

  return (
    <Card className="flex flex-col">
      {inventoryPart.imageUrl && (
        <Image
          src={inventoryPart.imageUrl}
          alt={part.name}
          width={320}
          height={180}
          className="aspect-video object-contain p-4 w-full"
        />
      )}
      <CardHeader className="flex-1">
        <CardDescription className="flex items-center gap-1">
          <div
            style={{ background: inventoryPart.color.hex }}
            className="w-4 h-4 rounded-md"
          />
          {inventoryPart.color.name} • {inventoryPart.quantity}
        </CardDescription>
        <CardTitle className="line-clamp-2">{part.name}</CardTitle>
      </CardHeader>
      <CardFooter className="gap-2 items-end justify-between">
        <Tooltip>
          <TooltipTrigger className="mr-auto">
            <Badge>
              <ToyBrick size={14} strokeWidth={2} className="mr-0.5" />
              {collectionInventoryPart.quantityFound} of{' '}
              {collectionInventoryPart.quantity}
            </Badge>
          </TooltipTrigger>
          <TooltipContent>
            <p>
              {collectionInventoryPart.quantityFound} parts found out of{' '}
              {collectionInventoryPart.quantity}
            </p>
          </TooltipContent>
        </Tooltip>
        <Dialog>
          <DialogTrigger>
            <Tooltip>
              <TooltipTrigger>
                <Button variant="ghost" size="icon">
                  <ToyBrick size={24} />
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>Add or remove parts</p>
              </TooltipContent>
            </Tooltip>
          </DialogTrigger>
          <DialogContent>
            <form onSubmit={onSubmit} className="grid gap-4">
              <DialogHeader>
                <DialogTitle>Add or remove parts</DialogTitle>
                <DialogDescription>
                  {collectionInventoryPart.quantityFound} of{' '}
                  {collectionInventoryPart.quantity} found
                </DialogDescription>
              </DialogHeader>
              <Label htmlFor="quantity">Quantity</Label>
              <div className="flex gap-2">
                <Input
                  type="number"
                  name="quantity"
                  min={0 - collectionInventoryPart.quantityFound}
                  max={
                    collectionInventoryPart.quantity -
                    collectionInventoryPart.quantityFound
                  }
                  defaultValue={collectionInventoryPart.quantity}
                />
                <Button type="submit" disabled={isLoading}>
                  Save
                </Button>
              </div>
              <DialogFooter>
                <Button
                  type="button"
                  variant="destructive"
                  onClick={() =>
                    addCollectionInventoryPart(
                      -collectionInventoryPart.quantityFound
                    )
                  }
                  disabled={isLoading}
                >
                  Remove all
                </Button>
                <Button
                  type="button"
                  variant="secondary"
                  onClick={() =>
                    addCollectionInventoryPart(
                      collectionInventoryPart.quantity -
                        collectionInventoryPart.quantityFound
                    )
                  }
                  disabled={isLoading}
                >
                  Found all
                </Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>
      </CardFooter>
    </Card>
  );
}

export { CollectionInventoryPartCard };

// src/routes/collection/[id]/collection-inventory-part-card.svelte
<script lang="ts">
  import { ToyBrick, Plus } from "lucide-svelte";
  import { Image } from "@unpic/svelte";
	
  import * as Card from "$lib/components/ui/card";
  import * as Tooltip from "$lib/components/ui/tooltip";
	import * as Dialog from "$lib/components/ui/dialog";
  import { Button } from "$lib/components/ui/button";
  import { Badge } from "$lib/components/ui/badge";
	import { Input } from "$lib/components/ui/input";
	import { Label } from "$lib/components/ui/label";
	import type { CollectionInventoryPart } from '$models/CollectionInventoryPart';
	import createAddCollectionInventoryPartMutation from "$mutations/addCollectionInventoryPart";

	export let collectionInventoryPart: CollectionInventoryPart;
	$: part = collectionInventoryPart.inventoryPart.part;
	$: addCollectionInventoryPartMutation = createAddCollectionInventoryPartMutation(collectionInventoryPart._id);

	let quantity = 1;
  let dialogOpen = false;
</script>

<Card.Root class="flex flex-col overflow-hidden">
	<figure class="bg-white border-b">
		<Image 
			src={collectionInventoryPart.inventoryPart.imageUrl}
			alt={part.name}
			width={256}
			aspectRatio={16 / 9}
			objectFit="contain"
			class="p-4 w-full mix-blend-multiply"
		/>
	</figure>
	<Card.Header class="flex-1">
		<Card.Description> {collectionInventoryPart.inventoryPart.color.name} • {part.category.name}</Card.Description>
		<Card.Title class="line-clamp-2">{part.name}</Card.Title>
	</Card.Header>
	<Card.Footer class="items-end">
		<Tooltip.Root>
			<Tooltip.Trigger class="mr-auto">
				<Badge>
					<ToyBrick size={14} class="mr-1" />
					{collectionInventoryPart.quantityFound} of{' '}
					{collectionInventoryPart.quantity}
				</Badge>
			</Tooltip.Trigger>
			<Tooltip.Content>
				<p>
					{collectionInventoryPart.quantityFound} parts found out of{' '}
					{collectionInventoryPart.quantity}
				</p>
			</Tooltip.Content>
		</Tooltip.Root>
		<Dialog.Root bind:open={dialogOpen}>
			<Dialog.Trigger>
				<Tooltip.Root>
					<Tooltip.Trigger>
						<Button
							variant="ghost"
							size="icon"
						>
							<Plus size={24} />
						</Button>
					</Tooltip.Trigger>
					<Tooltip.Content>
						<p>Add or remove parts</p>
					</Tooltip.Content>
				</Tooltip.Root>
			</Dialog.Trigger>
			<Dialog.Content>
				<Dialog.Header>
					<Dialog.Title>Add or remove parts</Dialog.Title>
					<Dialog.Description>
						{collectionInventoryPart.quantityFound} of{' '}
						{collectionInventoryPart.quantity} found
					</Dialog.Description>
				</Dialog.Header>
				<Label for="quantity">Quantity</Label>
				<div class="flex gap-2">
					<Input
						type="number"
						name="quantity"
						bind:value={quantity}
						min={0 - collectionInventoryPart.quantityFound}
						max={
							collectionInventoryPart.quantity -
							collectionInventoryPart.quantityFound
						}
					/>
					<Button 
						disabled={$addCollectionInventoryPartMutation.isPending}
						on:click={() => {
							$addCollectionInventoryPartMutation.mutate(quantity)
							dialogOpen = false;
						}}
					>
						{quantity > 0 ? 'Add' : 'Remove'}
					</Button>
				</div>
				<Dialog.Footer>
					<Button
						variant="destructive"
						on:click={() => {
							$addCollectionInventoryPartMutation.mutate(
								-collectionInventoryPart.quantityFound
							)
							dialogOpen = false;
						}}
						disabled={$addCollectionInventoryPartMutation.isPending || collectionInventoryPart.quantityFound === 0}
					>
						Remove all
					</Button>
					<Button
						variant="secondary"
						on:click={() => {
							$addCollectionInventoryPartMutation.mutate(
								collectionInventoryPart.quantity -
									collectionInventoryPart.quantityFound
							)
							dialogOpen = false;
						}}
						disabled={$addCollectionInventoryPartMutation.isPending || collectionInventoryPart.quantityFound === collectionInventoryPart.quantity}
					>
						Found all
					</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	</Card.Footer>
</Card.Root>
