// app/Navbar.tsx
'use client';

import { FC, PropsWithChildren } from 'react';
import Image from 'next/image';
import { LucideIcon, Home, Blocks, Bookmark, Search } from 'lucide-react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

interface NavbarLinkProps {
  href: string;
  icon: LucideIcon;
  exact?: boolean;
}

const NavbarLink: FC<PropsWithChildren<NavbarLinkProps>> = ({
  href,
  icon: Icon,
  children,
  exact = false,
}) => {
  const pathName = usePathname();
  const active = pathName
    ? exact
      ? pathName === href
      : pathName.startsWith(href)
    : false;

  return (
    <Link
      href={href}
      className={`h-16 px-6 text-sm flex gap-2 items-center font-medium transition-all duration-75 ${
        active ? 'text-primary' : 'text-muted-foreground hover:text-foreground'
      }`}
    >
      <Icon size={22} />
      {children}
    </Link>
  );
};

const Navbar: FC = () => (
  <header className="border-b">
    <div className="container px-4 flex justify-between items-center">
      <Link href="/" className="text-xl font-semibold tracking-tighter flex gap-2 items-center">
        <Image
          src="/logo.png"
          alt="Bricksort"
          width={32}
          height={32}
        />
        Bricksort
      </Link>
      <nav className="flex divide-x border-x">
        <NavbarLink icon={Home} href="/" exact>
          Home
        </NavbarLink>
        <NavbarLink icon={Search} href="/browse" exact>
          Browse
        </NavbarLink>
        <NavbarLink icon={Blocks} href="/collection">
          Collection
        </NavbarLink>
        <NavbarLink icon={Bookmark} href="/wishlist">
          Wishlist
        </NavbarLink>
      </nav>
    </div>
  </header>
);

export default Navbar;

// src/routes/navbar.svelte
<script lang="ts">
	import { toggleMode, mode } from 'mode-watcher';
	import { Home, Blocks, Bookmark, Search, Moon, Sun } from 'lucide-svelte';
  import { signOut } from '@auth/sveltekit/client';
  import { Image } from "@unpic/svelte";

  import { page } from '$app/stores';
  import { handleSignIn } from '$lib/auth';
  import { Button } from "$lib/components/ui/button";
	import NavbarLink from "./navbar-link.svelte";
</script>

<header class="border-b">
	<div class="container px-4 flex justify-between items-center">
		<a href="/" class="text-xl font-semibold tracking-tighter flex gap-2 items-center">
			<Image
				width={32}
				height={32}
				src="/logo.png"
				alt="Bricksort"
			/>
			Bricksort
		</a>
		<div class="flex gap-4 items-center">
			<nav class="flex divide-x border-x">
				<NavbarLink href="/" exact>
					<Home size={24} />
					Home
				</NavbarLink>
				<NavbarLink href="/browse" exact>
					<Search size={24} />
					Browse
				</NavbarLink>
				<NavbarLink href="/collection">
					<Blocks size={24} />
					Collection
				</NavbarLink>
				<NavbarLink href="/wishlist">
					<Bookmark size={24} />
					Wishlist
				</NavbarLink>
			</nav>
			<Button
				size="icon"
				on:click={toggleMode}
			>
				{#if $mode === 'dark'}
					<Moon size={24} />
				{:else}
					<Sun size={24} />
				{/if}
			</Button>
			{#if $page.data.session}
				<Button
					on:click={() => signOut()}
				>
					Sign out
				</Button>
				{#if $page.data.session.user?.image}
					<Image
						width={40}
						height={40}
						src={$page.data.session.user.image}
						alt="Profile picture"
						class="rounded-full"
					/>
				{/if}
			{:else}
				<Button on:click={() => handleSignIn()}>
					Sign in
				</Button>
			{/if}
		</div>
	</div>
</header>
