// app/navbar.tsx
'use client';

import { FC, PropsWithChildren } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Home, Search, LucideIcon, User, Folder } from 'lucide-react';
import { cn } from '@/lib/utils';

interface NavbarItemProps {
  href: string;
  icon: LucideIcon;
  exact?: boolean;
}

const NavbarItem: FC<PropsWithChildren<NavbarItemProps>> = ({
  href,
  icon: Icon,
  exact = false,
  children,
}) => {
  const pathname = usePathname();
  const isActive = exact ? pathname === href : pathname.startsWith(href);

  return (
    <Link
      href={href}
      className={cn(
        'flex flex-col items-center justify-center gap-2 py-2',
        isActive ? 'text-primary' : 'text-muted-foreground hover:text-primary'
      )}
    >
      <Icon size={20} />
      <span className="text-xs font-medium">{children}</span>
    </Link>
  );
};

export const Navbar = () => {
  return (
    <nav className="grid grid-cols-4 border-t">
      <NavbarItem href="/" icon={Home} exact>
        Home
      </NavbarItem>
      <NavbarItem href="/browse" icon={Search}>
        Browse
      </NavbarItem>
      <NavbarItem href="/collection" icon={Folder}>
        Collection
      </NavbarItem>
      <NavbarItem href="/profile" icon={User}>
        Profile
      </NavbarItem>
    </nav>
  );
};

// src/routes/navbar.svelte
<script lang="ts">
	import { toggleMode, mode } from 'mode-watcher';
	import { Home, Blocks, Bookmark, Search, Moon, Sun } from 'lucide-svelte';
  import { signOut } from '@auth/sveltekit/client';
  import { Image } from "@unpic/svelte";

  import { page } from '$app/stores';
  import { handleSignIn } from '$lib/auth';
  import { Button } from "$lib/components/ui/button";
	import NavbarLink from "./navbar-link.svelte";
</script>

<header class="border-b">
	<div class="container px-4 flex justify-between items-center">
		<a href="/" class="text-xl font-semibold tracking-tighter flex gap-2 items-center">
			<Image
				width={32}
				height={32}
				src="/logo.png"
				alt="Bricksort"
			/>
			Bricksort
		</a>
		<div class="flex gap-4 items-center">
			<nav class="flex divide-x border-x">
				<NavbarLink href="/" exact>
					<Home size={24} />
					Home
				</NavbarLink>
				<NavbarLink href="/browse" exact>
					<Search size={24} />
					Browse
				</NavbarLink>
				<NavbarLink href="/collection">
					<Blocks size={24} />
					Collection
				</NavbarLink>
				<NavbarLink href="/wishlist">
					<Bookmark size={24} />
					Wishlist
				</NavbarLink>
			</nav>
			<Button
				size="icon"
				on:click={toggleMode}
			>
				{#if $mode === 'dark'}
					<Moon size={24} />
				{:else}
					<Sun size={24} />
				{/if}
			</Button>
			{#if $page.data.session}
				<Button
					on:click={() => signOut()}
				>
					Sign out
				</Button>
				{#if $page.data.session.user?.image}
					<Image
						width={40}
						height={40}
						src={$page.data.session.user.image}
						alt="Profile picture"
						class="rounded-full"
					/>
				{/if}
			{:else}
				<Button on:click={() => handleSignIn()}>
					Sign in
				</Button>
			{/if}
		</div>
	</div>
</header>
