// src/routes/collection/[id]/collection-inventory-part-card.svelte
<script lang="ts">
  import { ToyBrick, Plus } from "lucide-svelte";
  import { Image } from "@unpic/svelte";
	
  import * as Card from "$lib/components/ui/card";
  import * as Tooltip from "$lib/components/ui/tooltip";
	import * as Dialog from "$lib/components/ui/dialog";
  import { Button } from "$lib/components/ui/button";
  import { Badge } from "$lib/components/ui/badge";
	import { Input } from "$lib/components/ui/input";
	import { Label } from "$lib/components/ui/label";
	import type { CollectionInventoryPart } from '$models/CollectionInventoryPart';
	import createAddCollectionInventoryPartMutation from "$mutations/addCollectionInventoryPart";

	export let collectionInventoryPart: CollectionInventoryPart;
	$: part = collectionInventoryPart.inventoryPart.part;
	$: addCollectionInventoryPartMutation = createAddCollectionInventoryPartMutation(collectionInventoryPart._id);

	let quantity = 1;
  let dialogOpen = false;
</script>

<Card.Root class="flex flex-col overflow-hidden">
	<figure class="bg-white border-b">
		<Image 
			src={collectionInventoryPart.inventoryPart.imageUrl}
			alt={part.name}
			width={256}
			aspectRatio={16 / 9}
			objectFit="contain"
			class="p-4 w-full mix-blend-multiply"
		/>
	</figure>
	<Card.Header class="flex-1">
		<Card.Description> {collectionInventoryPart.inventoryPart.color.name} • {part.category.name}</Card.Description>
		<Card.Title class="line-clamp-2">{part.name}</Card.Title>
	</Card.Header>
	<Card.Footer class="items-end">
		<Tooltip.Root>
			<Tooltip.Trigger class="mr-auto">
				<Badge>
					<ToyBrick size={14} class="mr-1" />
					{collectionInventoryPart.quantityFound} of{' '}
					{collectionInventoryPart.quantity}
				</Badge>
			</Tooltip.Trigger>
			<Tooltip.Content>
				<p>
					{collectionInventoryPart.quantityFound} parts found out of{' '}
					{collectionInventoryPart.quantity}
				</p>
			</Tooltip.Content>
		</Tooltip.Root>
		<Dialog.Root bind:open={dialogOpen}>
			<Dialog.Trigger>
				<Tooltip.Root>
					<Tooltip.Trigger>
						<Button
							variant="ghost"
							size="icon"
						>
							<Plus size={24} />
						</Button>
					</Tooltip.Trigger>
					<Tooltip.Content>
						<p>Add or remove parts</p>
					</Tooltip.Content>
				</Tooltip.Root>
			</Dialog.Trigger>
			<Dialog.Content>
				<Dialog.Header>
					<Dialog.Title>Add or remove parts</Dialog.Title>
					<Dialog.Description>
						{collectionInventoryPart.quantityFound} of{' '}
						{collectionInventoryPart.quantity} found
					</Dialog.Description>
				</Dialog.Header>
				<Label for="quantity">Quantity</Label>
				<div class="flex gap-2">
					<Input
						type="number"
						name="quantity"
						bind:value={quantity}
						min={0 - collectionInventoryPart.quantityFound}
						max={
							collectionInventoryPart.quantity -
							collectionInventoryPart.quantityFound
						}
					/>
					<Button 
						disabled={$addCollectionInventoryPartMutation.isPending}
						on:click={() => {
							$addCollectionInventoryPartMutation.mutate(quantity)
							dialogOpen = false;
						}}
					>
						{quantity > 0 ? 'Add' : 'Remove'}
					</Button>
				</div>
				<Dialog.Footer>
					<Button
						variant="destructive"
						on:click={() => {
							$addCollectionInventoryPartMutation.mutate(
								-collectionInventoryPart.quantityFound
							)
							dialogOpen = false;
						}}
						disabled={$addCollectionInventoryPartMutation.isPending || collectionInventoryPart.quantityFound === 0}
					>
						Remove all
					</Button>
					<Button
						variant="secondary"
						on:click={() => {
							$addCollectionInventoryPartMutation.mutate(
								collectionInventoryPart.quantity -
									collectionInventoryPart.quantityFound
							)
							dialogOpen = false;
						}}
						disabled={$addCollectionInventoryPartMutation.isPending || collectionInventoryPart.quantityFound === collectionInventoryPart.quantity}
					>
						Found all
					</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	</Card.Footer>
</Card.Root>

// components/Card/CollectionInventoryPartCard.tsx
import { FC, useState } from 'react';

import { ExtendedCollectionInventoryPart } from '../../models/CollectionInventoryPart';
import useAddCollectionInventoryPart from '../../mutations/useAddCollectionInventoryPart';
import Card from '.';
import Image from 'next/image';

interface CollectionInventoryPartCardProps {
    collectionInventoryPart: ExtendedCollectionInventoryPart;
}

const CollectionInventoryPartCard: FC<CollectionInventoryPartCardProps> = ({ collectionInventoryPart }) => {
    const { mutate: addCollectionInventoryPart, isLoading } = useAddCollectionInventoryPart(collectionInventoryPart);
    const [quantity, setQuantity] = useState(1);
    const [isModalOpen, setIsModalOpen] = useState(false);

    const inventoryPart = collectionInventoryPart.inventoryPart;
    const part = inventoryPart.part;
    const color = inventoryPart.color;

    return (
        <>
            <Card
                title={part.name}
                body={`${color.name} • ${collectionInventoryPart.quantityFound} of ${collectionInventoryPart.quantity} found`}
                imgSrc={inventoryPart.imageUrl}
                imgAlt={part.name}
                onClick={() => setIsModalOpen(true)}
            />
            <div className={`modal ${isModalOpen ? 'modal-open' : ''}`}>
                <div className="modal-box">
                    <h3 className="font-bold text-lg">{part.name}</h3>
                    <p className="py-4">{`${color.name} • ${collectionInventoryPart.quantityFound} of ${collectionInventoryPart.quantity} found`}</p>
                    {inventoryPart.imageUrl && (
                        <figure>
                            <Image
                                src={inventoryPart.imageUrl}
                                alt={part.name}
                                width={300}
                                height={300}
                                className="p-4 object-contain w-full aspect-video mix-blend-multiply"
                                priority={true}
                            />
                        </figure>
                    )}
                    <div className="max-w-full flex flex-col gap-2">
                        <div className="form-control">
                            <label className="label">
                                <span className="label-text">Quantity to add or remove</span>
                            </label>
                            <input
                                className="input input-bordered"
                                type="number"
                                value={quantity}
                                onChange={(e) => setQuantity(parseInt(e.target.value))}
                            />
                        </div>
                        <div className="grid grid-cols-2 gap-2">
                            <button
                                className="btn"
                                disabled={collectionInventoryPart.quantityFound + quantity > collectionInventoryPart.quantity}
                                onClick={() => {
                                    addCollectionInventoryPart(quantity);
                                    setQuantity(1);
                                    setIsModalOpen(false);
                                }}
                            >
                                add
                            </button>
                            <button
                                className="btn"
                                disabled={collectionInventoryPart.quantityFound <= 0}
                                onClick={() => {
                                    addCollectionInventoryPart(-quantity);
                                    setQuantity(1);
                                    setIsModalOpen(false);
                                }}
                            >
                                remove
                            </button>
                        </div>
                        <button
                            className="btn"
                            disabled={collectionInventoryPart.quantityFound >= collectionInventoryPart.quantity}
                            onClick={() => addCollectionInventoryPart(collectionInventoryPart.quantity - collectionInventoryPart.quantityFound)}
                        >
                            found all
                        </button>
                    </div>
                    <div className="modal-action">
                        <button className="btn btn-primary" onClick={() => setIsModalOpen(false)}>
                            close
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
};

export default CollectionInventoryPartCard;
