// components/set-card.tsx
import { FC } from 'react';
import Image from 'next/image';
import { Plus, ToyBrick } from 'lucide-react';
import { type Set } from '@/models/set';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Card,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from '@/components/ui/drawer';

interface SetCardProps {
  set: Set;
}

export const SetCard: FC<SetCardProps> = ({ set }) => (
  <Card>
    <Image
      src={set.imageUrl}
      alt={set.name}
      width={500}
      height={500}
      className="p-4 w-full aspect-video object-contain"
    />
    <CardHeader>
      <CardTitle>{set.name}</CardTitle>
      <CardDescription>
        {set.theme.name} • {set.year}
      </CardDescription>
    </CardHeader>
    <CardFooter className="items-end justify-between">
      <Badge className="items-center gap-1" variant="secondary">
        <ToyBrick size={16} />
        {set.partCount} parts
      </Badge>
      <Drawer>
        <DrawerTrigger>
          <Button size="icon">
            <Plus size={20} />
          </Button>
        </DrawerTrigger>
        <DrawerContent>
          <DrawerHeader>
            <DrawerTitle>Add to your collection</DrawerTitle>
            <DrawerDescription>
              Do you want to add this set to your collection?
            </DrawerDescription>
          </DrawerHeader>
          <DrawerFooter>
            <Button>Yes</Button>
            <DrawerClose>
              <Button variant="outline" className="w-full">
                Cancel
              </Button>
            </DrawerClose>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>
    </CardFooter>
  </Card>
);

// src/routes/browse/set-card.svelte
<script lang="ts">
  import { ToyBrick, Blocks, BookmarkPlus } from "lucide-svelte";
  import { toast } from "svelte-sonner";
  import { Image } from "@unpic/svelte";

  import { page } from '$app/stores';
  import * as Card from "$lib/components/ui/card";
  import * as Tooltip from "$lib/components/ui/tooltip";
  import { Button } from "$lib/components/ui/button";
  import { Badge } from "$lib/components/ui/badge";
	import type { Set } from '$models/Set';

	export let set: Set;
</script>

<Card.Root class="flex flex-col">
	<a href="/sets/{set._id}">
		<Image 
			src={set.imageUrl}
			alt={set.name}
			width={256}
			aspectRatio={16 / 9}
			objectFit="contain"
			class="p-4 w-full"
		/>
	</a>
	<Card.Header class="flex-1">
		<Card.Description> #{set._id.split('-')[0]} • {set.theme.name} • {set.year}</Card.Description>
		<a href="/sets/{set._id}">
			<Card.Title class="line-clamp-2 hover:underline">{set.name}</Card.Title>
		</a>
	</Card.Header>
	<Card.Footer class="items-end">
		<Tooltip.Root>
			<Tooltip.Trigger class="mr-auto">
				<Badge>
					<ToyBrick size={14} class="mr-1" />
					{set.partCount}
				</Badge>
			</Tooltip.Trigger>
			<Tooltip.Content>
				<p>{set.partCount} pieces</p>
			</Tooltip.Content>
		</Tooltip.Root>
		<Tooltip.Root>
			<Tooltip.Trigger>
				<Button
					variant="ghost"
					size="icon"
					on:click={() =>
						toast('Added to collection', {
							description: 'Go to your collection to start adding parts',
						})
					}
				>
					<Blocks size={24} />
				</Button>
			</Tooltip.Trigger>
			<Tooltip.Content>
				<p>Add to collection</p>
			</Tooltip.Content>
		</Tooltip.Root>
		<Tooltip.Root>
			<Tooltip.Trigger>
				<Button
					variant="ghost"
					size="icon"
					on:click={() =>
						toast('Added to wishlist', {
							description: 'You can view your wishlist in your profile',
						})
					}
				>
					<BookmarkPlus size={24} />
				</Button>
			</Tooltip.Trigger>
			<Tooltip.Content>
				<p>Add to wishlist</p>
			</Tooltip.Content>
		</Tooltip.Root>
	</Card.Footer>
</Card.Root>
